### ISSUE TITLE
SS doesn't understand -f.

### ISSUE THREAD

**Issue by GUIpsp** [md-5/SpecialSource#13]
`Caused by: java.lang.IllegalArgumentException: Invalid access visibility: -f
        at net.md_5.specialsource.AccessChange.<init>(AccessChange.java:107)
        at net.md_5.specialsource.AccessMap.addAccessChange(AccessMap.java:138)
        at net.md_5.specialsource.AccessMap.addAccessChange(AccessMap.java:134)
        at net.md_5.specialsource.AccessMap.loadAccessTransformer(AccessMap.java:83)
        at net.md_5.specialsource.AccessMap.loadAccessTransformer(AccessMap.java:88)
        at net.md_5.specialsource.AccessMap$loadAccessTransformer.call(Unknown Source)`

`-f aqw.cE`

**Comment by md-5** [comment]
Use -final please

**Comment by GUIpsp** [comment]
One year after :stuck_out_tongue:
