### ISSUE TITLE
SS throws a ZipException

### ISSUE THREAD

**Issue by PizzaCrust** [md-5/SpecialSource#37]
```
java.util.zip.ZipException: duplicate entry: net/minecraft/command/CommandExecuteAt$1.class
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:215)
	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
	at net.md_5.specialsource.JarRemapper.remapJar(JarRemapper.java:213)
	at net.md_5.specialsource.SpecialSource.main(SpecialSource.java:269)
	at net.pizzacrust.mcpinjector.Injector.main(Injector.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by md-5** [comment]
I'm gonna bet that your input jar has duplicate zip entries. Mojang even managed to release a snapshot like this one time.

**Comment by PizzaCrust** [comment]
Idk, when I open up with WinRAR; I didn't see any duplicate entries.

**Comment by PizzaCrust** [comment]
![classes](https://cloud.githubusercontent.com/assets/15954148/13214493/8ac2872e-d982-11e5-8a58-3823bbd36e1e.png)

**Comment by md-5** [comment]
I'm not sure of tools that would show them. All I can suggest is your  input jar is bad.

**Comment by PizzaCrust** [comment]
I don't know how to remove the duplicate entries.

**Comment by PizzaCrust** [comment]
Here is my source code: https://gist.github.com/PizzaCrust/4959aa397364fefde139

**Comment by TheGreatKetchup** [comment]
I am getting this error if I have a .csrg file that goes as follows:

```
abx Monster
abz Monster
```

Perhaps a cleaner error message would help.
